language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "LkRxjts8iEuzqICGo0ShhqP+i6I5YDn7WQYmHgTxYv8f9c5We3MePomsF9OWf2QiSfWRLgd6ax+s1hxgqMQo8q0m8pP24BNQexQLjjeyJHAjHiEk3Xe3+HDK2+vzGznJvwfajm3l1k6Fe867LxLfbviNKBEOf5kgOrfHGeo5SgWOWr8t0p1OuFldl6TL36EM8qsUpafXNiyYR2nvSiBFrAj2ypven8OBijO5zSECd6gnz4goJv/D3bgA/ILqGu+WUlqtt6NFzjcmUSHKg1gMvWcV6pKzMVjHZW5dmqQRmtTT/e5jZOqB8CHjCbrn1K1lsrZ1IdsjLtpxJNEqTJ+W64F1yXJFjtMs2nPOR83H4IIoS8oGjYbQ2mApzsgI/54m5iExA0+3xPCQAJfCSoSXoE7xVVP6cYTRbKg8oubUK2gmMsGNxliNUiqv88zGLZ1j8wtdkRypJmR/z1jSFruXTG2P/XbDjF8toHsux/fYblWil1xGnyVjd1IQZO6R57N/KW+OGvZXXCetclPRscfRBaJa7AkDO4tvhsAN5P4HHQxWFhTRl5GH7PGtGy2wQ26V7rcR05AhsiFT1832gxHeTat+lTOiWh2HWMZLnLYrjZi+9PXBSOBV3fTguG4VWjIwtjPy15Y7s6Apj73N1yXzuXA2bTxCG04lIwQqUQuyf8I="
  api_key: # b58c
    secure: "RxX47Vz2jwJqXWJbj0npL30B0lS78IeSf92m8KjGGU33saR3L37SO7H4n6Ax+bN/5qabw0xOfp/+kJ/CZry/fyYdoN7JkO74IrT+jDgJehJcfBYsZ/wkXY8XYGS1VSkNe9cX70PEQ2I/aZU55B1lvDFdSVFZeZoZ/03AXhCFgj2r8rSY3nHVFEjl9j5anjMRCrkBQf/d2vwE/C83NDXTl74QI30KXftlGWktX30hDSwr8B9RI4JNnWRO0Y5do+RLTzmbiOgxeUhediUSaxadxp7LgSOZBtwfzcFyDNMAY9qruKdJ/UwkuyhTQfo1Kx7rEPVaI1HXs3i3IfgPBC69Ip+VaLceoxcUZPjX5D+mxRieZ38qErY5v/09BPzj8wQVASVzqPL+j5I/ldf8/Q7yfr1tktICHpIBt4yqTWgLuygsz0e2oGr1GJMmACxUnNnlqoeA8uUs41cc/6tNIGg0kOUOqUGEfQibCXsuccFerycxO/qyhD7k4jui1IuATUn2pCEYq/l/Y2dddQ/sGmT1ZZa38a/tGoTqLOgi3d3TYVGw+DujsOwr7+0koV6co3cvp/c+6d98XnEGmAhB5R/j4hi4VekgVy/vZQXchw7y7Omrtga+cVI5UjQKTgQruBiszvk0b8rbugjsZUGanlIEkcKk8JN8/LPx7KyENiUAnnI="
  on:
    tags: true
    node: lts/*
